services:

  ContaClaraDb:
    container_name: ContaClara
    build: .
    image: postgres:latest
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=conta_clara
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./volume:/var/lib/postgresql/data